# Generated by Django 4.2.1 on 2023-06-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_producto_preciocosto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('dv', models.CharField(default='', max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=50)),
                ('region', models.IntegerField(choices=[[0, 'Región de Arica y Parinacota'], [1, 'Región de Tarapacá'], [2, 'Región de Antofagasta'], [3, 'Región de Atacama'], [4, 'Región de Coquimbo'], [5, 'Región de Valparaíso'], [6, 'Región Metropolitana'], [7, "Región de O'Higgins"], [8, 'Región del Maule'], [9, 'Región del Ñuble'], [10, 'Región del Biobío'], [11, 'Región de La Araucanía'], [12, 'Región de Los Ríos'], [13, 'Región de Los Lagos'], [14, 'Región de Aysén'], [15, 'Región de Magallanes']])),
                ('telefono', models.CharField(max_length=15)),
                ('nivelEducacion', models.IntegerField(choices=[[0, 'Magister'], [1, 'Doctor'], [2, 'Profesional'], [3, 'Otro']])),
            ],
        ),
    ]
